auto_start_c2sim: false
c2sim_server:
  host: 192.168.254.71
  password: v0lgenau
  rest_port: 8080
  stomp_port: 61613
  submitter_id: SWC2SGW
  topic: /topic/C2SIM
  use_oidp: false
  version: 4.8.4.9
logging:
  backup_count: 5
  log_file: sw_c2sim_gw.log
  log_level: INFO
  max_log_size: 10485760
sitaware_server:
  api_port: 443
  default_layer: default
  host: 192.168.254.51
  password: admin
  username: admin
  verify_ssl: false
translation:
  default_sidc: SHGPUCAW-------
